# Compose v2 não precisa da chave "version:"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: arbitrium
      POSTGRES_USER: arbitrium
      POSTGRES_PASSWORD: arbitrium
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arbitrium -d arbitrium"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10

  django:
    build: .
    container_name: django_app
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://arbitrium:arbitrium@postgres:5432/arbitrium
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CELERY_TIMEZONE: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns: ["8.8.8.8","1.1.1.1"]  # ajuda na resolução DNS para CS.MONEY

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A Arbitrium_CS worker -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://arbitrium:arbitrium@postgres:5432/arbitrium
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CELERY_TIMEZONE: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns: ["8.8.8.8","1.1.1.1"]

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A Arbitrium_CS beat -l info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://arbitrium:arbitrium@postgres:5432/arbitrium
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      CELERY_TIMEZONE: America/Sao_Paulo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns: ["8.8.8.8","1.1.1.1"]

volumes:
  pg_data:
