# Generated by Django 5.2.5 on 2025-09-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_inventory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_alvo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
            options={
                'unique_together': {('item', 'inventory')},
            },
        ),
    ]
