# Generated by Django 5.2.5 on 2025-09-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pricealvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
