# Generated by Django 5.2.5 on 2025-09-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='csmoney_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='csmoney_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='csmoney_price_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
