# Generated by Django 5.2.5 on 2025-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_inventory_csmoney_id_inventory_csmoney_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
